cache:
  paths:
    - frontend/c12-grupo-6/node_modules

stages:
  - build
  - run

variables:
  S3_BUCKET_PROD: ${BUCKET_PROD}

.npm_build:
  image: node:14.15.1
  script: |
    cd frontend/c12-grupo-6
    npm install # Install all dependencies
    npm run build # Build command     
  artifacts:
    paths:
      - ./frontend/c12-grupo-6/build
      

npm_prod:
  extends: .npm_build
  stage: build
  before_script:
    - export APP_ENV="prod"
  only:
    refs:
      - develop

.deploy_aws:
  image: python:latest
  #when: manual
  script: |
    cd frontend/c12-grupo-6
    pip install awscli #Install awscli tools
    aws s3 sync ./build/ s3://${S3_BUCKET}


deploy_prod:
  extends: .deploy_aws
  stage: run
  dependencies:
    - npm_prod
  before_script:
    - export S3_BUCKET=${S3_BUCKET_PROD}
  only:
    refs:
      - develop


