server:
  port: 8081
  servlet:
    context-path: /digitalbooking/lodgings/api/v1
spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
    version: 1.0.0